---

sudo: required
language: ruby
dist: trusty
rvm:
  - 2.5.1

before_install:
  - sudo apt-get install python-setuptools
  - sudo easy_install pip
  - sudo pip install ansible

install: gem install serverspec

before_script:
  - ansible-playbook spec/ansible.yml

script: 
  - rake spec
