---

sudo: required
language: ruby
dist: trusty
rvm:
  - 2.5.1

before_install:
  - sudo apt-get install -y software-properties-common
  - yes | sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible

install: gem install serverspec rake

before_script:
  - ansible --version

script: 
  - rake spec
