---

sudo: required

language: ruby

dist: xenial

rvm:
  - 2.5.1

before_install:
  - gem install serverspec
  - sudo apt-get install -y python2.7 python-setuptools
  - sudo easy_install pip
  - sudo pip install ansible

install:
  - ansible-playbook -vv -i spec/inventory spec/playbook.yml

script: 
  - rake spec
  - ansible-playbook -i spec/inventory spec/playbook.yml | grep 'changed=0'
