---

sudo: required
language: ruby
dist: xenial
rvm:
  - 2.5.1

before_install:
  - sudo apt-get install -y python2.7
  - sudo apt-get install -y python-setuptools
  - sudo easy_install pip
  - sudo pip install ansible

install: gem install serverspec

before_script:
  - ansible-playbook -vvv -i spec/inventory spec/ansible.yml

script: 
  - rake spec
  - ansible-playbook -i spec/inventory spec/ansible.yml
