---

sudo: required

language: ruby

dist: xenial

rvm:
  - 2.5.1

before_install:
  - gem install serverspec
  - sudo easy_install pip
  - sudo pip install ansible

install:
  - ansible-playbook -vv -i spec/inventory spec/playbook.yml --syntax-check
  - ansible-playbook -vv -i spec/inventory spec/playbook.yml -l localhost

before_script:
  - echo "require 'serverspec'\nset :backend, :exec" > spec/localhost/aaa_spec.rb

script: 
  - rake spec
  - idempotence=$(mktemp)
  - "ansible-playbook -vv -i spec/inventory spec/playbook.yml -l localhost | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
