---

sudo: required

language: ruby

dist: xenial

rvm:
  - 2.5.1

before_install:
  - gem install serverspec
  - sudo easy_install pip
  - sudo pip install ansible

install:
  - ansible-playbook -vv -i spec/inventory spec/playbook.yml --syntax-check
  - ansible-playbook -vv -i spec/inventory spec/playbook.yml -l localhost
  - ls /etc/apt/
  - ls /etc/apt/sources.list.d

script: 
  - rake spec
  - ansible-playbook -i spec/inventory spec/playbook.yml | grep 'changed=0'
