---

- name: Install apt key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  tags:
    - nodejs

- name: Install apt source
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }} xenial main"
  tags:
    - nodejs

# NOTE: npm is included
- name: Install nodejs packages
  become: yes
  apt:
    name: "nodejs={{ node_version | regex_replace('x','') }}*"
    update_cache: yes
  tags:
    - nodejs

- include: yarn.yml
  when: install_yarn
  tags:
    - nodejs
    - yarn
