---

# Ansibles apt_key only downloads the key when it is needed. Sometimes the key changes
# (see https://github.com/yarnpkg/yarn/issues/6865) and Ansible won't pick up on the change
# @docs https://yarnpkg.com/en/docs/install#debian-stable
- name: Install apt key
  become: yes
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -"
  args:
    warn: false
  changed_when: false
  tags:
    - yarn

- name: Install apt source
  become: yes
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
  tags:
    - yarn

- name: Install packages
  become: yes
  apt:
    name: "yarn"
    update_cache: yes
  tags:
    - yarn
